const Data = [
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
	{
		name: "asd",
		surname: "asd",
		email: "asd",
		phone: "asd",
		description: "asd",
		date: "01.25.2002",
	},
];
export default Data;
